spring:
  profiles:
    active: local
  application:
    name: menu-management

---

spring:
  profiles: local
  data.mongodb:
    host: mongo
    port: 27017
    database: menu-management
    authentication-database: admin
    username: ampos
    password: ampospass

server:
  port: 8080
  servlet:
    context-path: /api

pagination:
  start: 0
  size: 10

eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
      preferSameZoneEureka: true