spring:
  profiles:
    active: local
  application:
    name: order-management

---

spring:
  profiles: local
  data.mongodb:
    host: localhost
    port: 27017
    authentication-database: admin
    database: order-management
    username: ampos
    password: ampospass

server:
  port: 8081
  servlet:
    context-path: /api

pagination:
  start: 0
  size: 10

eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true

service:
  menu: menu-management
api:
  menu: api/menus